### PR TITLE
Fix MNT: Add noarch: python

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
This should fix the `noarch` PR https://github.com/conda-forge/csbdeep-feedstock/pulls

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
@conda-forge-admin, please rerender

**Comment by psobolewskiPhD** [comment]
OK, so the `noarch` is trickier than I thought vs. pip `any`.
So maybe this isn't the way to go, because it requires no selectors at all, not even for versions.
This makes the existing csbdeep requirement of h5py <3 for python <3.9 is a deal-breaker.

The TF issue that made this a requirement is closed, because it's been fixed in TF 2.4.x, and TF TF 2.1 isn't supported. 
So one solution is setting TF >2.4 here, but this of course precludes support for old TF envs...

So yeah, I can totally understand if you want to scrap these two PRs.

**Comment by uschmidt83** [comment]
Sorry @psobolewskiPhD, I don't know what's going on here. What am I supposed to do?

**Comment by psobolewskiPhD** [comment]
I don't either! 🤣 
Basically it seems like on conda-forge to go `noarch`—have a package with no specific architecture it makes it really restrictive in terms of what you can set for other params, like python version, etc. So it's not like the `csbdeep` pypi package that JustWorks.
`noarch` here would make macOS arm64 easier—probably? still don't understand why the migrator hasn't worked—but at a cost of requiring TF>2.4, which may not be acceptable?
I'm not clear on what the `napari` plugin ecosystem is going to be/do—despite the new NAP2—so probably the best strategy is to just kill these 2 PRs and see what happens. 
StarDist works wonderfully via pip and so does stardist-napari.

**Comment by uschmidt83** [comment]
Ok, thanks for the explanation! I'll close these PRs for now, we can re-open/visit them if need-be.

**Pull request closed without merging**
